from krsp.models.Appointment import Appointment
from krsp.models.Chat import Chat
from krsp.models.ChatRoom import ChatRoom
from krsp.models.Doctor import Doctor
from krsp.models.MedicalHistory import MedicalHistory
from krsp.models.Order import Order
from krsp.models.Patient import Patient
from krsp.models.Ratings import Ratings
from krsp.models.Scheme import Scheme
from krsp.models.User import User
from krsp.models.OTP import OTP
from krsp.models.Services import upload_path
from krsp.models.InfoPage import InfoPage
