# Generated by Django 4.1.7 on 2023-04-27 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krsp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('pageId', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.TextField(max_length=100000)),
                ('page_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ratings',
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('fk_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krsp.doctor')),
                ('fk_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krsp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('fk_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krsp.chatroom')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.UniqueConstraint(fields=('fk_doctor', 'fk_patient'), name='unique_key_client_advisor'),
        ),
    ]
